# Generated by Django 5.1 on 2024-09-08 01:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='tag', max_length=255, verbose_name='Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for an article.', primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the article', max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(default='')),
                ('template_filename', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('reading_minutes', models.IntegerField(default=3)),
                ('public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the record was created.', verbose_name='Created at')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('tags', models.ManyToManyField(blank=True, to='main.tag')),
            ],
        ),
    ]
